version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip install -r requirements.txt
      - run:
          name: Build and test - Scripts des cours
          command: ./.circleci/run_scripts_python.sh
      - run:
          name: Build and test - Scripts du module
          command: ./.circleci/run_scripts_package.sh

